### DISCUSSION TITLE
Can we use two different images for light and dark theme in sidebar?

### DISCUSSION THREAD

**Discussion by SumithChandran** [docsifyjs/docsify#1768] [Q&A] [answered]
There is dark and light theme switcher available for docsify. Is there a way to use 2 images for sidebar one light theme and other for dark theme?

**Comment by sy-records** [comment, marked as answer]
Sidebar images? Are you referring to the logo?

Dark mode will show a pink logo.
![](https://user-images.githubusercontent.com/7565692/35311593-3edd9102-00f2-11e8-98fb-38be1d0e650f.png)

Add it to index.html: 
```html
<style>
    @media (prefers-color-scheme: light) {
        .app-name-link img {
            content: url('https://raw.githubusercontent.com/docsifyjs/docsify/develop/docs/_media/icon.svg');
        }
    }

    @media (prefers-color-scheme: dark) {
        .app-name-link img {
            content: url('https://user-images.githubusercontent.com/7565692/35311593-3edd9102-00f2-11e8-98fb-38be1d0e650f.png');
        }
    }
</style>
```

> Usually only the `prefers-color-scheme: dark` related style needs to be set separately.

### docsify-darklight-theme

If you are using `docsify-darklight-theme`, it needs to be modified to look like this.

```css
@media (prefers-color-scheme: light) {
    .app-name-link img {
        content: var(--docsify_logo_url,url('https://raw.githubusercontent.com/docsifyjs/docsify/develop/docs/_media/icon.svg'));
    }
}

@media (prefers-color-scheme: dark) {
    .app-name-link img {
        content: var(--docsify_logo_url,url('https://user-images.githubusercontent.com/7565692/35311593-3edd9102-00f2-11e8-98fb-38be1d0e650f.png'));
    }
}
```

and add config option

```js
    window.$docsify = {
        darklightTheme: {
            dark: {
                docsify_logo_url: 'url(https://user-images.githubusercontent.com/7565692/35311593-3edd9102-00f2-11e8-98fb-38be1d0e650f.png)'
            },
            light: {
                docsify_logo_url: 'url(https://raw.githubusercontent.com/docsifyjs/docsify/develop/docs/_media/icon.svg)'
            }
        }
    }
```

**Reply by SumithChandran** [reply]
@sy-records 
I copied the exact code which you shared. When I previewed it I was only getting the dark theme logo(AKA the pink logo). The light theme logo is not working. It's still displaying the pink logo for white as well as dark.

This is the code i used:
[index.zip](https://github.com/docsifyjs/docsify/files/8217535/index.zip)

**Reply by sy-records** [reply]
It is normal for me to use your index.html as well.
Can't reproduce the problem you are talking about, what system are you using? Not macOS?

**Reply by SumithChandran** [reply]
@sy-records I am using windows system.

**Reply by sy-records** [reply]
Please provide a full repo or source code.

A dark mode in effect means normal, and a light mode you can use the default.

**Reply by SumithChandran** [reply]
@sy-records 
Here is the repo i created for testing
[Test Moke.zip](https://github.com/docsifyjs/docsify/files/8220047/Test.Moke.zip)

**Reply by sy-records** [reply]
Are you referring to the fact that the logo doesn't change when you click here to switch?
<img width="194" alt="image" src="https://user-images.githubusercontent.com/33931153/157594334-96186d06-30cb-48a8-94d1-f3814d3ffac2.png">

**Reply by SumithChandran** [reply]
Yes

**Reply by SumithChandran** [reply]
It worked😀.
@sy-records thanks for digging deep through this and helping me.
Nice work👌

**Comment by mre** [comment]
Just in case someone finds this (already answered) thread again, if you use `docsify-darklight-theme`, you can simply add a variable as described above and refer to that in your style:

```javascript
window.$docsify = {
  darklightTheme: {
    dark: {
      docsify_logo_url: "url(/_media/logo_dark.svg)"
    },
    light: {
      docsify_logo_url: "url(/_media/logo.svg)"
    },
  },
};
```

```scss
<style>
.cover-main img {
  content: var(--docsify_logo_url);
}
</style>
```

Notably you don't need to use media selectors (`@media (prefers-color-scheme: dark)` etc.) to make it work.
Change the image selector (`.cover-main img `) to whatever element you want to modify based on the theme.
