### ISSUE TITLE
Deploy to google app engine

### ISSUE THREAD

**Issue by Prajwal-Koirala** [docsifyjs/docsify#1161]
Need help

**Comment by anikethsaha** [comment]
Please give more info and fill the issue template

**Comment by Prajwal-Koirala** [comment]
@anikethsaha i need some instructions on how to deploy this on google cloud app engine.

**Comment by anikethsaha** [comment]
this is just a js file. you would host it as you host your static site.

**Comment by Prajwal-Koirala** [comment]
@anikethsaha i tried but it doesn't work.
can u give it a try and maybe post the working code.
app engine standard environment is completely free

**Comment by anikethsaha** [comment]
> @anikethsaha i tried but it doesn't work.
> can u give it a try and maybe post the working code.
> app engine standard environment is completely free

sorry as I am a bit out of time for the next few days/weeks.

You can ask this in our hitter chatroom, someone might help .

**Comment by Prajwal-Koirala** [comment]
ok

**Comment by Prajwal-Koirala** [comment]
package.json
```
{
    "name": "NAME",
    "version": "0.0.1",
    "private": true,
    "homepage": "https://NAME.COM",
    "description": "Main website for name.com",
    "main": "app.js",
    "scripts": {
        "start": "node app.js"
    },
    "repository": {
        "type": "git",
        "url": "git+https://github.com/NAME/NAME.git",
        "bugs": "https://github.com/NAME/NAME/issues",
        "license": "MIT"
    },
    "keywords": [
        "NAME.com",
        "api.NAME.com"
    ],
    "author": {
        "name": "Your Name Here",
    },
    "dependencies": {
        "node-static": "^0.7.11"
    }
}
```
app.js
```
var static = require('node-static');

var file = new static.Server('./docs');

require('http').createServer(function(request, response) {
    request.addListener('end', function() {

        file.serve(request, response);
    }).resume();
}).listen(8080);
```
app.yaml
```
service: default
runtime: nodejs12
env: standard
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
network: {}
```

**Comment by Prajwal-Koirala** [comment]
deploy to app engine on golang.

main.go
```
package main

import (
	"log"
	"net/http"
)

func main() {

	http.Handle("/", http.FileServer(http.Dir("./docs")))

	log.Fatal(http.ListenAndServe(":8080", nil))
}
```
app.yaml
```
service: default
runtime: go113
env: standard
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
network: {}
```
