### ISSUE TITLE
Can I custom "cover show" of "class=ready" background style

### ISSUE THREAD

**Issue by Reagan1947** [docsifyjs/docsify#1485]
#### What problem does this feature solve?
As you can see, at the begin of ready, the background calss`(class= "cover show")`  style would be a linear-gradient like `background: linear-gradient(to left bottom, hsl(188, 100%, 85%) 0%,hsl(171, 100%, 85%) 100%);`

I wish  I can custom the cover ready style.

#### How should this be implemented in your opinion?
Maybe I can choice that use the default cover style or show the color I want.

#### Are you willing to work on this yourself?
Willing!

**Comment by sy-records** [comment]
You can add css in index.html.

For example, removing the background

```css
  <style>
    .cover {
      background:unset!important;
    }
  </style>
```
