### ISSUE TITLE
docsify-auto-sidebar -d as Github Action?

### ISSUE THREAD

**Issue by TheXRMonk** [docsifyjs/docsify#1610]
> @indaviande You can use this tool [docsify-tools](https://www.npmjs.com/package/docsify-tools) via `npm i docsify-tools -g` and `docsify-auto-sidebar -d docs`.

I struggled with using this as a Github Action (as I'm not familiar with node.js), but I finally made it work if anyone is interested:
I added a package.json to the root;
```
{
  "name": "docs",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "docsify-auto-sidebar -d ../*name-of-repo*"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "docsify-tools": "^1.0.20"
  }
}
```
with *name-of-repo* being your repo name.
Then the action looks like this;
```
name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-sidebar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm i docsify-tools
        
      - name: Make Sidebar
        run: npm test
        
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto-updated Sidebar
```
I couldn't call the `docsify-auto-sidebar -d ../*name-of-repo*` command directly from github actions, so had to do it this way.

If there's a better way please enlighten me. :)

_Originally posted by @TheXRMonk in https://github.com/docsifyjs/docsify/issues/610#issuecomment-872850450_
