### ISSUE TITLE
I want to know how to add numbers to these automatically?

### ISSUE THREAD

**Issue by insoxin** [docsifyjs/docsify#1614]
![image](https://user-images.githubusercontent.com/19371836/126513774-b8c962cb-918f-4f59-bb8d-0d2cd1bdeac7.png)

**Comment by sy-records** [comment]
You can use CSS.

```css
      .sidebar-nav ul>li>ul>li {
        list-style-type: decimal !important;
      }
```
