### ISSUE TITLE
Keep heading selectable and use seperate element to link target

### ISSUE THREAD

**Issue by LIGMATV** [docsifyjs/docsify#2447]
## Feature request

I want the heading link target using the seperate element  (**#**) like in Vitepress.
![vitepress dev_guide_deploy](https://github.com/docsifyjs/docsify/assets/143163098/317df70c-826d-4a40-8ee6-b673b4e08cf3)

#### Problem or desire

The headings was hard to selectable and more like an link, also ugly.
![localhost_62999_ (1)](https://github.com/docsifyjs/docsify/assets/143163098/b4bdacb7-9b6c-4ca1-a7ad-3cc874138787)

#### Proposal

The headings was like other texts, and selectable. The link target element will visible when the heading hovered.
![localhost_62999_ (2)](https://github.com/docsifyjs/docsify/assets/143163098/cd4844ef-e50d-4a49-b3fc-4819d20cf0d6)

#### Implementation

This is the code i use to make the screenshot demo.

```diff
<h1 id="quick-start">
   <a href="#/?id=quick-start" data-id="quick-start" class="anchor">
+        <div class="heading-anchor"></div>
+    </a>
        <span>Quick start</span>
-    </a>
</h1>
```

```css
        .anchor:hover {
            text-decoration: none;
        }
        .markdown-section h1 {
            padding-left: 1rem;
            margin-left: -1.42rem;
        }
        .markdown-section h1:hover .heading-anchor {
            opacity: 1;
        }
        .heading-anchor {
            opacity: 0;
            transition: color .25s, opacity .25s;
        }
        .heading-anchor::before {
            content: '#';
            margin-left: -1rem;
        }
```

**Comment by sy-records** [comment]
You can implement this using css.

```markdown
      .markdown-section .anchor{
        text-decoration: none;
        position: relative;
      }

      .markdown-section .anchor:before{
        content: '#';
        opacity: 0;
        transition: opacity 0.3s;
        position: absolute;
        left: -0.8em;
      }

      .markdown-section .anchor:hover::before {
        opacity: 1;
      }
```

**Comment by LIGMATV** [comment]
@sy-records @paulhibbitts
I just do new experiment and this how to create the text of heading still selectable :

```css
              .markdown-section .anchor {
                  text-decoration: none;
                  position: relative;
                  user-select: text;
                  -webkit-user-drag: none;
                  cursor: auto;
              }

              .markdown-section .anchor:before {
                  content: '#';
                  opacity: 0;
                  transition: opacity 0.3s;
                  position: absolute;
                  left: -0.8em;
                  cursor: pointer;
              }

              .markdown-section .anchor:hover::before {
                  opacity: 1;
              }
```

With using [`user-select: text`](https://caniuse.com/mdn-css_properties_user-select_text) and [`-webkit-user-drag`](https://caniuse.com/mdn-css_properties_-webkit-user-drag).
