### ISSUE TITLE
How to automatically generate a sidebar based on the directory structure?

### ISSUE THREAD

**Issue by frapples** [docsifyjs/docsify#610]
Hi:
  Thank you for creating such a great tool. 

I have a problem now, I use it to preview my notes, and my notes are organized by directory.
Whenever I rename the note or add a note, I need to update the _sierbar file synchronously.

Is there any way to automatically generate a _sidebar file based on the directory structure?

Or does docsify provide a plugin API for extension?

Thank you!

**Comment by petrk94** [comment]
I wrote a bash script which auto generate the README.md for subfolders of docsify.
In theory, it should be even possible to auto generate the sidebar with a bash script, but for this you need to run it manually or to make another bash script which run the autogen bash script and afterwards start the docsify.
Does this help you?

**Comment by xiaoluhong** [comment]
@petrk94 Hi, Can I see your bash script? thank you.

**Comment by petrk94** [comment]
Hi @xiaoluhong,
thanks for your interest, but I dont have this script longer, due the project required more customization, I dropped it.

**Comment by advename** [comment]
I've wrote a python script for this:
```
import os
files = [f for f in os.listdir('.') if os.path.isfile(f)]

sidebar_file = open('_sidebar.md', 'w')

for file in files:
	if ".md" in file:
		name = file.split(".md")
		file = file.replace(" ", "%20")
		sidebar_file.write( f"* [{name[0]}]({file})\n" )

sidebar_file.close()
```
Simply place all your markdown files in the /docs directory and run this script in a python shell or save it as a python file like *create_sidebar.py* and run it with `python create_sidebar.py`

**Comment by indaviande** [comment]
I've got the following error line while running the pytohon script :
`➜  docsify git:(master) ✗ python create_sidebar.py   
  File "create_sidebar.py", line 10
    sidebar_file.write( f"* [{name[0]}]({file})\n" )
                                                 ^
SyntaxError: invalid syntax`

**Comment by advename** [comment]
Can't help you there, mine works.

**Comment by brisa-pedronetto** [comment]
@indaviande try running `python3 create_sidebar.py` 👍

**Comment by brisa-pedronetto** [comment]
Also, I added an improved version of @indaviande's script here: https://gist.github.com/brisa-pedronetto/ca0adc0e8d5550cb34ce5144ec2b305f

**Comment by ZetaoYang** [comment]
@indaviande  You can use this tool [docsify-tools](https://www.npmjs.com/package/docsify-tools) via `npm i docsify-tools -g` and `docsify-auto-sidebar -d docs`.

**Comment by TheXRMonk** [comment]
> @indaviande You can use this tool [docsify-tools](https://www.npmjs.com/package/docsify-tools) via `npm i docsify-tools -g` and `docsify-auto-sidebar -d docs`.

I struggled with using this as a Github Action (as I'm not familiar with node.js), but I finally made it work if anyone is interested:
I added a package.json to the root;
```
{
  "name": "docs",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "docsify-auto-sidebar -d ../Virsabi.Core.Docs"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "docsify-tools": "^1.0.20"
  }
}
```
Then the action looks like this;
```
name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-sidebar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm i docsify-tools
        
      - name: Make Sidebar
        run: npm test
        
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto-updated Sidebar
```
I couldn't call the `docsify-auto-sidebar -d ../Virsabi.Core.Docs` command directly from github actions, so had to do it this way.

If there's a better way please enlighten me. :)
