### ISSUE TITLE
Prismjs supports line numbers and sepcific line highlight

### ISSUE THREAD

**Issue by toavinar** [docsifyjs/docsify#771]
Is it possible to integrate to docsify PrismJS 
[line-highlight](https://prismjs.com/plugins/line-highlight/) and [line-numbers](https://prismjs.com/plugins/line-numbers/) plugins ? 

Thank's for this amazing project, great work !

**Comment by timaschew** [comment]
Sure, but it seems that you need to write the `code` and `pre` elements manually.

**Comment by toavinar** [comment]
Of course, here is my workaround for line-numbers : 

`index.html` : 
```javascript 
<script>
    window.$docsify = {
      markdown: {        
            code: function(code, lang) {
                return ('<pre data-lang="'+lang+'"><code class="line-numbers language-'+lang+'">'+code+'</code></pre>')
            }
        },
      plugins: [
          function (hook, vm) {
              hook.doneEach(function (html) {                
                Prism.highlightAll();
              })
          }
      ]
</script>
```

It works but copy clipboard plugin doesn't works anymore. I keep working on it.

**Comment by Guyutongxue** [comment]
This [workaround](https://github.com/docsifyjs/docsify/issues/771#issuecomment-464719382) doesn't work now. I discovered that the problem is caused by `overflow` attribute. So here's my solution:

First change the default rendering behavior to add class `line-numbers`:

```js
window.$docsify {
    markdown: {
        renderer: {
          /* Change code block rendering. Add line-numbers class.*/
          code: function (code, lang) {
            let cc = document.createElement('code');
            cc.textContent = code;
            cc.setAttribute('class', 'language-' + lang);
            return '<pre data-lang="' + lang + '" class="line-numbers">' + cc.outerHTML + '</pre>';
          }
        }
      }
}
```
Then I need to change that incorrect `overflow` by an another CSS:
```css
/*  
 * Fix line number in code block. 
 * Change this overflow attr to <pre> not the <code>.
 */
.markdown-section pre[data-lang] {
    overflow: auto !important;
}
.markdown-section pre[data-lang] code {
    overflow: visible;
}
```
At last I need to change the `padding` of `.line-numbers` to align with codes:
```CSS
.line-numbers .line-numbers-rows {
    border-right : 2px solid white;
    /* Fix paddings to align with code.*/
    padding: 2.2em 0; /* Same as code block */
}
```

And finally those code-numbers were showed correctly.
